server:
  port: 8989
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: ORACLE
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: NOGESH
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
